/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedMentalHealthDiaryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addEntry"
      | "entryExists"
      | "getEntry"
      | "getEntryCount"
      | "getLastEntryDate"
      | "getMentalStateHandle"
      | "getStressHandle"
      | "protocolId"
      | "validateDateRange"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "EntryAdded" | "EntryDecrypted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addEntry",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "entryExists",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntry",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastEntryDate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMentalStateHandle",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStressHandle",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validateDateRange",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addEntry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "entryExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEntry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastEntryDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMentalStateHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStressHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateDateRange",
    data: BytesLike
  ): Result;
}

export namespace EntryAddedEvent {
  export type InputTuple = [
    user: AddressLike,
    date: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, date: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    date: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntryDecryptedEvent {
  export type InputTuple = [user: AddressLike, date: BigNumberish];
  export type OutputTuple = [user: string, date: bigint];
  export interface OutputObject {
    user: string;
    date: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedMentalHealthDiary extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedMentalHealthDiary;
  waitForDeployment(): Promise<this>;

  interface: EncryptedMentalHealthDiaryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addEntry: TypedContractMethod<
    [
      date: BigNumberish,
      encryptedMentalStateHandle: BytesLike,
      encryptedStressHandle: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  entryExists: TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [boolean],
    "view"
  >;

  getEntry: TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [
      [string, string, bigint] & {
        mentalStateHandle: string;
        stressHandle: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEntryCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getLastEntryDate: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getMentalStateHandle: TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [string],
    "view"
  >;

  getStressHandle: TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [string],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  validateDateRange: TypedContractMethod<
    [user: AddressLike, startDate: BigNumberish, endDate: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addEntry"
  ): TypedContractMethod<
    [
      date: BigNumberish,
      encryptedMentalStateHandle: BytesLike,
      encryptedStressHandle: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "entryExists"
  ): TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntry"
  ): TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [
      [string, string, bigint] & {
        mentalStateHandle: string;
        stressHandle: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntryCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLastEntryDate"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMentalStateHandle"
  ): TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStressHandle"
  ): TypedContractMethod<
    [user: AddressLike, date: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "validateDateRange"
  ): TypedContractMethod<
    [user: AddressLike, startDate: BigNumberish, endDate: BigNumberish],
    [boolean],
    "view"
  >;

  getEvent(
    key: "EntryAdded"
  ): TypedContractEvent<
    EntryAddedEvent.InputTuple,
    EntryAddedEvent.OutputTuple,
    EntryAddedEvent.OutputObject
  >;
  getEvent(
    key: "EntryDecrypted"
  ): TypedContractEvent<
    EntryDecryptedEvent.InputTuple,
    EntryDecryptedEvent.OutputTuple,
    EntryDecryptedEvent.OutputObject
  >;

  filters: {
    "EntryAdded(address,uint256,uint256)": TypedContractEvent<
      EntryAddedEvent.InputTuple,
      EntryAddedEvent.OutputTuple,
      EntryAddedEvent.OutputObject
    >;
    EntryAdded: TypedContractEvent<
      EntryAddedEvent.InputTuple,
      EntryAddedEvent.OutputTuple,
      EntryAddedEvent.OutputObject
    >;

    "EntryDecrypted(address,uint256)": TypedContractEvent<
      EntryDecryptedEvent.InputTuple,
      EntryDecryptedEvent.OutputTuple,
      EntryDecryptedEvent.OutputObject
    >;
    EntryDecrypted: TypedContractEvent<
      EntryDecryptedEvent.InputTuple,
      EntryDecryptedEvent.OutputTuple,
      EntryDecryptedEvent.OutputObject
    >;
  };
}
